# Generated by Django 6.0.1 on 2026-02-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
