# Generated by Django 6.0.2 on 2026-02-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_options_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', ' can view history')]},
        ),
    ]
